allow-lan: false
dns:
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  - 8.8.8.8
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fallback:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
  - tls://8.8.4.4
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
  ipv6: false
  listen: 127.0.0.1:53553
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
external-controller: 127.0.0.1:29090
find-process-mode: 'off'
global-client-fingerprint: chrome
ipv6: false
log-level: info
mixed-port: 28888
mode: global
proxies:
- cipher: aes-256-cfb
  name: 原clash订阅已过期
  obfs: http_simple
  obfs-param: bing.com
  password: crossxx
  port: 8890
  protocol: origin
  protocol-param: ''
  server: baidu.com
  type: ssr
- cipher: aes-256-cfb
  name: 或者服务器无法访问
  obfs: http_simple
  obfs-param: bing.com
  password: crossxx
  port: 8890
  protocol: origin
  protocol-param: ''
  server: baidu.com
  type: ssr
- cipher: aes-256-cfb
  name: 搜索倚天剑clash
  obfs: http_simple
  obfs-param: bing.com
  password: crossxx
  port: 8890
  protocol: origin
  protocol-param: ''
  server: baidu.com
  type: ssr
- cipher: aes-256-cfb
  name: 或登录https://a.aiguobit.com
  obfs: http_simple
  obfs-param: bing.com
  password: crossxx
  port: 8890
  protocol: origin
  protocol-param: ''
  server: baidu.com
  type: ssr
- cipher: aes-256-cfb
  name: 备用https://a.hidexx.com
  obfs: http_simple
  obfs-param: bing.com
  password: crossxx
  port: 8890
  protocol: origin
  protocol-param: ''
  server: baidu.com
  type: ssr
- cipher: aes-256-cfb
  name: 打开https://github.com/crossxx-labs/free-proxy
  obfs: http_simple
  obfs-param: bing.com
  password: crossxx
  port: 8890
  protocol: origin
  protocol-param: ''
  server: baidu.com
  type: ssr
- cipher: aes-256-cfb
  name: 获取免费账号
  obfs: http_simple
  obfs-param: bing.com
  password: crossxx
  port: 8890
  protocol: origin
  protocol-param: ''
  server: baidu.com
  type: ssr
proxy-groups:
- interval: 300
  name: AUTO
  proxies:
  - 原clash订阅已过期
  - 或者服务器无法访问
  - 搜索倚天剑clash
  - 或登录https://a.aiguobit.com
  - 备用https://a.hidexx.com
  - 打开https://github.com/crossxx-labs/free-proxy
  - 获取免费账号
  tolerance: 100
  type: url-test
  url: http://connect.rom.miui.com/generate_204
rules:
- MATCH,AUTO
skip-auth: true
tcp-concurrent: true
unified-delay: true
