allow-lan: false
dns:
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enable: true
  enhanced-mode: redir-host
  fallback:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 240.0.0.0/4
  ipv6: false
  listen: 127.0.0.1:53553
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
external-controller: 127.0.0.1:29090
find-process-mode: 'off'
global-client-fingerprint: chrome
ipv6: false
log-level: info
mixed-port: 28888
mode: global
proxies:
- cipher: aes-256-cfb
  name: 原clash订阅已过期
  obfs: http_simple
  obfs-param: bing.com
  password: crossxx
  port: 8890
  protocol: origin
  protocol-param: ''
  server: baidu.com
  type: ssr
- cipher: aes-256-cfb
  name: 或者服务器无法访问
  obfs: http_simple
  obfs-param: bing.com
  password: crossxx
  port: 8890
  protocol: origin
  protocol-param: ''
  server: baidu.com
  type: ssr
- cipher: aes-256-cfb
  name: 搜索倚天剑clash
  obfs: http_simple
  obfs-param: bing.com
  password: crossxx
  port: 8890
  protocol: origin
  protocol-param: ''
  server: baidu.com
  type: ssr
- cipher: aes-256-cfb
  name: 或登录https://a.aiguobit.com
  obfs: http_simple
  obfs-param: bing.com
  password: crossxx
  port: 8890
  protocol: origin
  protocol-param: ''
  server: baidu.com
  type: ssr
- cipher: aes-256-cfb
  name: 备用https://a.hidexx.com
  obfs: http_simple
  obfs-param: bing.com
  password: crossxx
  port: 8890
  protocol: origin
  protocol-param: ''
  server: baidu.com
  type: ssr
- cipher: aes-256-cfb
  name: 打开https://github.com/crossxx-labs/free-proxy
  obfs: http_simple
  obfs-param: bing.com
  password: crossxx
  port: 8890
  protocol: origin
  protocol-param: ''
  server: baidu.com
  type: ssr
- cipher: aes-256-cfb
  name: 获取免费账号
  obfs: http_simple
  obfs-param: bing.com
  password: crossxx
  port: 8890
  protocol: origin
  protocol-param: ''
  server: baidu.com
  type: ssr
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: 剩余流量：40.68 GB
  port: 8443
  reality-opts:
    public-key: 2a0ONLRiBeHJdr9qCruq5tPVf8_3c4fmZsg7YQorFSE
    short-id: 04d59340
  server: 1sg001.344211.cc
  servername: www.python.org
  skip-cert-verify: false
  tls: true
  type: vless
  udp: false
  uuid: 4251c10e-f273-4d73-9348-61dad545743d
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: 距离下次重置剩余：9 天
  port: 8443
  reality-opts:
    public-key: 2a0ONLRiBeHJdr9qCruq5tPVf8_3c4fmZsg7YQorFSE
    short-id: 04d59340
  server: 1sg001.344211.cc
  servername: www.python.org
  skip-cert-verify: false
  tls: true
  type: vless
  udp: false
  uuid: 4251c10e-f273-4d73-9348-61dad545743d
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: 套餐到期：2027-03-20
  port: 8443
  reality-opts:
    public-key: 2a0ONLRiBeHJdr9qCruq5tPVf8_3c4fmZsg7YQorFSE
    short-id: 04d59340
  server: 1sg001.344211.cc
  servername: www.python.org
  skip-cert-verify: false
  tls: true
  type: vless
  udp: false
  uuid: 4251c10e-f273-4d73-9348-61dad545743d
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: vless新加坡01
  port: 8443
  reality-opts:
    public-key: 2a0ONLRiBeHJdr9qCruq5tPVf8_3c4fmZsg7YQorFSE
    short-id: 04d59340
  server: 1sg001.344211.cc
  servername: www.python.org
  skip-cert-verify: false
  tls: true
  type: vless
  udp: false
  uuid: 4251c10e-f273-4d73-9348-61dad545743d
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: vless台湾01
  port: 8443
  reality-opts:
    public-key: 2a0ONLRiBeHJdr9qCruq5tPVf8_3c4fmZsg7YQorFSE
    short-id: 04d59340
  server: tw1.459292.xyz
  servername: www.python.org
  skip-cert-verify: false
  tls: true
  type: vless
  udp: false
  uuid: 4251c10e-f273-4d73-9348-61dad545743d
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: vless台湾02
  port: 8443
  reality-opts:
    public-key: 2a0ONLRiBeHJdr9qCruq5tPVf8_3c4fmZsg7YQorFSE
    short-id: 04d59340
  server: tw06.459292.xyz
  servername: www.python.org
  skip-cert-verify: false
  tls: true
  type: vless
  udp: false
  uuid: 4251c10e-f273-4d73-9348-61dad545743d
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: vless台湾03
  port: 8443
  reality-opts:
    public-key: 2a0ONLRiBeHJdr9qCruq5tPVf8_3c4fmZsg7YQorFSE
    short-id: 04d59340
  server: tw5.459921.xyz
  servername: www.microsoft.com
  skip-cert-verify: false
  tls: true
  type: vless
  udp: false
  uuid: 4251c10e-f273-4d73-9348-61dad545743d
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: vless台湾04
  port: 8443
  reality-opts:
    public-key: 2a0ONLRiBeHJdr9qCruq5tPVf8_3c4fmZsg7YQorFSE
    short-id: 04d59340
  server: tw4.459921.xyz
  servername: www.python.org
  skip-cert-verify: false
  tls: true
  type: vless
  udp: false
  uuid: 4251c10e-f273-4d73-9348-61dad545743d
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: vless台湾05
  port: 8443
  reality-opts:
    public-key: 2a0ONLRiBeHJdr9qCruq5tPVf8_3c4fmZsg7YQorFSE
    short-id: 04d59340
  server: 5gzdx.344211.cc
  servername: www.python.org
  skip-cert-verify: false
  tls: true
  type: vless
  udp: false
  uuid: 4251c10e-f273-4d73-9348-61dad545743d
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: vless台湾06
  port: 8443
  reality-opts:
    public-key: 2a0ONLRiBeHJdr9qCruq5tPVf8_3c4fmZsg7YQorFSE
    short-id: 04d59340
  server: tw3.344211.cc
  servername: www.python.org
  skip-cert-verify: false
  tls: true
  type: vless
  udp: false
  uuid: 4251c10e-f273-4d73-9348-61dad545743d
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: vless台湾08
  port: 8443
  reality-opts:
    public-key: 2a0ONLRiBeHJdr9qCruq5tPVf8_3c4fmZsg7YQorFSE
    short-id: 04d59340
  server: tw11.344211.cc
  servername: www.python.org
  skip-cert-verify: false
  tls: true
  type: vless
  udp: false
  uuid: 4251c10e-f273-4d73-9348-61dad545743d
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: vless香港05HKT
  port: 8443
  reality-opts:
    public-key: 2a0ONLRiBeHJdr9qCruq5tPVf8_3c4fmZsg7YQorFSE
    short-id: 04d59340
  server: hkt05.344211.cc
  servername: www.python.org
  skip-cert-verify: false
  tls: true
  type: vless
  udp: false
  uuid: 4251c10e-f273-4d73-9348-61dad545743d
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: vless美国01aws
  port: 8443
  reality-opts:
    public-key: 2a0ONLRiBeHJdr9qCruq5tPVf8_3c4fmZsg7YQorFSE
    short-id: 04d59340
  server: us001.459292.xyz
  servername: www.python.org
  skip-cert-verify: false
  tls: true
  type: vless
  udp: false
  uuid: 4251c10e-f273-4d73-9348-61dad545743d
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: vless美国02aws
  port: 8443
  reality-opts:
    public-key: 2a0ONLRiBeHJdr9qCruq5tPVf8_3c4fmZsg7YQorFSE
    short-id: 04d59340
  server: us002.459292.xyz
  servername: www.python.org
  skip-cert-verify: false
  tls: true
  type: vless
  udp: false
  uuid: 4251c10e-f273-4d73-9348-61dad545743d
- cipher: chacha20-ietf-poly1305
  name: IPv6香港01ss
  password: 4251c10e-f273-4d73-9348-61dad545743d
  port: 8080
  server: 2401:b60:e0ce:20::1
  type: ss
  udp: false
- name: 有20多个节点，不够请到官网使用文档，下载最新的客户端
  password: 4251c10e-f273-4d73-9348-61dad545743d
  port: 8080
  server: 1.1.1.1
  sni: 1.1.1.1
  type: trojan
  udp: false
- name: 客户端设置，开启IPv6 ，用手机流量试下
  password: 4251c10e-f273-4d73-9348-61dad545743d
  port: 8080
  server: 1.1.1.1
  sni: 1.1.1.1
  type: trojan
  udp: false
- name: 电报群https://t.me/feiniaoyunjichang
  password: 4251c10e-f273-4d73-9348-61dad545743d
  port: 820
  server: 1.1.1.1
  sni: 1.1.1.1
  type: trojan
  udp: false
- name: 防失联页https://github.com/feiniaoyun
  password: 4251c10e-f273-4d73-9348-61dad545743d
  port: 820
  server: 2.2.2.2
  sni: 2.2.2.2
  type: trojan
  udp: false
proxy-groups:
- name: AUTO
  proxies:
  - 原clash订阅已过期
  - 或者服务器无法访问
  - 搜索倚天剑clash
  - 或登录https://a.aiguobit.com
  - 备用https://a.hidexx.com
  - 打开https://github.com/crossxx-labs/free-proxy
  - 获取免费账号
  - 剩余流量：40.68 GB
  - 距离下次重置剩余：9 天
  - 套餐到期：2027-03-20
  - vless新加坡01
  - vless台湾01
  - vless台湾02
  - vless台湾03
  - vless台湾04
  - vless台湾05
  - vless台湾06
  - vless台湾08
  - vless香港05HKT
  - vless美国01aws
  - vless美国02aws
  - IPv6香港01ss
  - 有20多个节点，不够请到官网使用文档，下载最新的客户端
  - 客户端设置，开启IPv6 ，用手机流量试下
  - 电报群https://t.me/feiniaoyunjichang
  - 防失联页https://github.com/feiniaoyun
  type: select
rules:
- MATCH,AUTO
skip-auth: true
tcp-concurrent: true
unified-delay: true
